export const bookMapping: { [key: string]: string } = {
    'ge': 'Genesis', 'gen': 'Genesis', 'genesis': 'Genesis',
    'exo': 'Exodus', 'exodus': 'Exodus',
    'lev': 'Leviticus', 'leviticus': 'Leviticus',
    'num': 'Numbers', 'nu': 'Numbers', 'numbers': 'Numbers',
    'deut': 'Deuteronomy', 'deu': 'Deuteronomy', 'dt': 'Deuteronomy', 'deuteronomy': 'Deuteronomy',
    'josh': 'Joshua', 'joshua': 'Joshua',
    'judg': 'Judges', 'jdg': 'Judges', 'judges': 'Judges',
    'ruth': 'Ruth', 'ru': 'Ruth',
    '1sam': '1 Samuel', '1samuel': '1 Samuel', '1 sam': '1 Samuel', '1sa': '1 Samuel',
    '2sam': '2 Samuel', '2samuel': '2 Samuel', '2 sam': '2 Samuel', '2sa': '2 Samuel',
    '1kgs': '1 Kings', '1kings': '1 Kings', '1 kgs': '1 Kings', '1ki': '1 Kings',
    '2kgs': '2 Kings', '2kings': '2 Kings', '2 kgs': '2 Kings', '2ki': '2 Kings',
    '1chr': '1 Chronicles', '1chronicles': '1 Chronicles', '1 ch': '1 Chronicles', '1chrn': '1 Chronicles',
    '2chr': '2 Chronicles', '2chronicles': '2 Chronicles', '2 ch': '2 Chronicles', '2chrn': '2 Chronicles',
    'ezra': 'Ezra', 'ez': 'Ezra',
    'neh': 'Nehemiah', 'nehemiah': 'Nehemiah',
    'esth': 'Esther', 'esther': 'Esther',
    'job': 'Job',
    'ps': 'Psalms', 'psalm': 'Psalms', 'psa': 'Psalms', 'psalms': 'Psalms',
    'prov': 'Proverbs', 'pro': 'Proverbs', 'proverbs': 'Proverbs',
    'eccl': 'Ecclesiastes', 'ecc': 'Ecclesiastes', 'ecclesiastes': 'Ecclesiastes',
    'song': 'Song of Solomon', 'songs': 'Song of Solomon', 'song of solomon': 'Song of Solomon',
    'isa': 'Isaiah', 'isaiah': 'Isaiah',
    'jer': 'Jeremiah', 'jeremiah': 'Jeremiah',
    'lam': 'Lamentations', 'lamentations': 'Lamentations',
    'ezek': 'Ezekiel', 'ezekiel': 'Ezekiel',
    'dan': 'Daniel', 'daniel': 'Daniel',
    'hos': 'Hosea', 'hosea': 'Hosea',
    'joel': 'Joel',
    'amos': 'Amos',
    'obad': 'Obadiah', 'obadiah': 'Obadiah',
    'jonah': 'Jonah',
    'micah': 'Micah',
    'nahum': 'Nahum',
    'hab': 'Habakkuk', 'habakkuk': 'Habakkuk',
    'zeph': 'Zephaniah', 'zephaniah': 'Zephaniah',
    'hag': 'Haggai', 'haggai': 'Haggai',
    'zech': 'Zechariah', 'zechariah': 'Zechariah',
    'mal': 'Malachi', 'malachi': 'Malachi',
    'matt': 'Matthew', 'mat': 'Matthew', 'matthew': 'Matthew',
    'mark': 'Mark',
    'luke': 'Luke', 'lk': 'Luke',
    'john': 'John', 'jn': 'John',
    'acts': 'Acts',
    'rom': 'Romans', 'romans': 'Romans',
    '1cor': '1 Corinthians', '1corinthians': '1 Corinthians', '1 cor': '1 Corinthians', '1co': '1 Corinthians',
    '2cor': '2 Corinthians', '2corinthians': '2 Corinthians', '2 cor': '2 Corinthians', '2co': '2 Corinthians',
    'gal': 'Galatians', 'galatians': 'Galatians',
    'eph': 'Ephesians', 'ephesians': 'Ephesians',
    'phil': 'Philippians', 'philippians': 'Philippians',
    'col': 'Colossians', 'colossians': 'Colossians',
    '1thess': '1 Thessalonians', '1thessalonians': '1 Thessalonians', '1 th': '1 Thessalonians', '1th': '1 Thessalonians',
    '2thess': '2 Thessalonians', '2thessalonians': '2 Thessalonians', '2 th': '2 Thessalonians',
    '1tim': '1 Timothy', '1timothy': '1 Timothy', '1 ti': '1 Timothy',
    '2tim': '2 Timothy', '2timothy': '2 Timothy', '2 ti': '2 Timothy',
    'titus': 'Titus',
    'philem': 'Philemon', 'philemon': 'Philemon',
    'heb': 'Hebrews', 'hebrews': 'Hebrews',
    'james': 'James',
    '1pet': '1 Peter', '1peter': '1 Peter', '1 pe': '1 Peter',
    '2pet': '2 Peter', '2peter': '2 Peter', '2 pe': '2 Peter',
    '1john': '1 John', '1 jn': '1 John',
    '2john': '2 John', '2 jn': '2 John',
    '3john': '3 John', '3 jn': '3 John',
    'jude': 'Jude',
    'rev': 'Revelation', 'revelation': 'Revelation'
  };
  